package com.example.trainingselenium.Utils;

public class Locators {
    public static final String ACCEPT_ALL_COOKIES = "button[data-testid='uc-accept-all-button']";
    public static final String REFUSE_ALL_COOKIES = "button[data-testid='uc-deny-all-button']";
    public static final String COUNTRY_DROPDOWN = "//span[contains(@class,'country-container ')]//span[contains(@class,'p-dropdown-trigger-icon')]";
    public static final String COUNTRY_INPUT = "//input[contains(@class,'p-inputtext p-component')]";
    public static final String CURRENCY_DROPDOWN = "//div[contains(@class,'currency-container')]//span[contains(@class,'p-dropdown-trigger-icon')]";
    public static final String START_SHOPPING_BUTTON = "//button[text()='Start Shopping']";
    public static final String COUNTRY_DROPDOWN_ITEM = "//li[contains(@class,'p-dropdown-item')][text()='%s']";
    public static final String CURRENCY_ITEM = "//div[contains(@class,'currency-switcher-panel')]//li[contains(@aria-label,'%s')]";
    public static final String SUBSCRIPTION_EMAIL_INPUT = "//input[contains(@id,'subscription-email')]";
    public static final String SELECT_COUNTRY = "//select[contains(@name,'country')]";
    public static final String SELECT_GENERAL_INTEREST = "//select[contains(@name,'general_interest')]";
    public static final String SELECT_PRODUCT_INTEREST = "//select[contains(@name,'product_interest')]";
    public static final String SUBSCRIBE_BUTTON = "//button[contains(@aria-label,'Sign Up')]";
    public static final String COUNTRY_OPTION_XPATH = SELECT_COUNTRY + "//option[text()='%s']";
    public static final String GENERAL_INTEREST_OPTION_XPATH = SELECT_GENERAL_INTEREST + "//option[text()='%s']";
    public static final String PRODUCT_INTEREST_OPTION_XPATH = SELECT_PRODUCT_INTEREST + "//option[text()='%s']";
    public static final String SELECT_COUNTRY_CURRENCY_SHOPPING = "//header//span[contains(text(),'Change')]";
    public static final String POPUP_MESSAGE_SUCCESS_OF_SUBSCRIBE = "//div[text()='Thank you for your subscription.']";
    public static final String ICON_PERSON_IN_HEADER = "//img[contains(@id,'account-link')]";
    public static final String FORGET_PASSWORD_LINK = "//form//span[contains(text(),'Forgotten the password?')]";
    public static final String EMAIL_RESET_PASSWORD_INPUT = "//div[contains(@class,'forgot-password-wrapper')]//input[contains(@name,'email')]";
    public static final String RESET_PASSWORD_BUTTON = "//div[contains(@class,'forgot-password-wrapper')]//button[contains(@aria-label,'Reset Password')]";
    public static final String EMAIL_YOP_MAIL_INPUT = "//input[contains(@name,'login')]";
    public static final String LOGIN_TO_YOP_MAIL_BUTTON = "//button[contains(@title,'Vérifier les mails @yopmail.com')]";
    public static final String NAME_IFRAME_MESSAGE_CONTENT = "ifmail";
    public static final String LINK_BUTTON_RESET_PASSWORD = "//div[@id='mail']//a[text()='Set a New Password']";
    public static final String NEW_PASSWORD_INPUT = "//input[@name='password']";
    public static final String REPEAT_PASSWORD_INPUT = "//input[@name='repeatPassword']";
    public static final String SAVE_NEW_PASSWORD_BUTTON = "//button[@aria-label='Save New password']";
    public static final String EMAIL_LOGIN_INPUT = "//div[contains(@class,'login-form')]//input[contains(@name,'email')]";
    public static final String PASSWORD_LOGIN_INPUT = "//div[contains(@class,'login-form')]//input[contains(@name,'password')]";
    public static final String LOGIN_BUTTON = "//div[contains(@class,'login-form')]//button[contains(@aria-label,'Log in to your Account')]";
    public static final String SUCCESS_LOGGED_MESSAGE_POPUP = "//div[contains(text(),'You are logged in!')]";
    public static final String LINK_DETAILS_USER_PAGE = "//span[contains(@class,'account-menu-section')]//a[@href='/my-account']";
    public static final String MESSAGE_RECEIVED_EMAIL_INSTRUCTION_RESET_PASSWORD = "//div[@class='forgot-password-wrapper']//p[contains(text(),'Check your inbox and follow the link')]";
    public static final String BACK_TO_LOGIN_BUTTON = "//div[contains(@class,'forgot-password-wrapper')]//button[contains(@aria-label,'Back to login')]";
    public static final String MESSAGE_FOR_PASSWORD_CHANGED_SUCCESS = "//div[contains(text(),'Your password has been reset successfully!')]";
    public static final String ICON_SEARCH_IN_HEADER = "//div[contains(@class,'header-menu')]//i[contains(@class,'icon-search')]";
    public static final String SEARCH_INPUT = "//div[contains(@class,'searchbox')]//input[contains(@placeholder,'Search')]";
    public static final String SEARCH_BUTTON = "//div[contains(@class,'searchbox')]//button[contains(@class,'search')]";
    public static final String SEARCH_RESULT_TEXT = "//div[contains(@class,'toolbar-tabs ')]//div[contains(text(),'results')]//span";
    public static final String ADD_TO_BAG_BUTTON = "//div[@data-sku='2002657']//button[contains(@class,'button add-basket')]";
    public static final String VIEW_BAG_CHECKOUT_BUTTON_IN_POPUP = "//div[contains(@class,'view-cart-button')]//button";
    public static final String LINK_PRODUCT_PDP = "//div[@data-sku='2002657']//div[contains(@class,'product-title')]//a";
    public static final String PRODUCT_PRICE_CART = "//div/preceding-sibling::div[text()='Available Now']";
}
